import Vue from 'vue'
import Router from 'vue-router'
Vue.use(Router)
const router = new Router({
  routes: [
    {
      path: '/login',
      name: 'login',
      component: ()=>import('@/views/login/index')
    },
    {
      path: '/',
      redirect:{
        name:"login"
      }
    },
    {
      path:'/main',
      name:'main',
      component:()=>import('@/views/layout/layout'),
      redirect:'main/index',
      children:[
          {
            path: 'index',
            name: 'index',
            chinise:'主页',
            items:'index',
            title:'主页',
            alone:true,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/index/mainIndex'),
          },
          {
            path: 'product_category',
            name: 'product_category',
            chinise:'选品',
            items:'article',
            title:"产品类别",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/article/productCategory'),
          },
          {
            path: 'fenlei',
            name: 'fenlei',
            chinise:'选品',
            items:'article',
            title:"产品分类",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/article/fenlei'),
          },
          {
            path: 'sku',
            name: 'sku',
            chinise:'选品',
            items:'article',
            title:"SKU",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/article/sku'),
          },
          {
            path: 'product_list',
            name: 'product_list',
            chinise:'选品',
            items:'article',
            title:"产品列表",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/article/productList'),
          },
          {
            path: 'shenhe',
            name: 'shenhe',
            chinise:'选品',
            items:'article',
            title:"产品审核",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/article/shenhe'),
          },
          {
            path: 'renling',
            name: 'renling',
            chinise:'设计',
            items:'icon',
            title:"产品认领",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/icon/renling'),
          },
          {
            path: 'pricegroup',
            name: 'pricegroup',
            chinise:'设计',
            items:'icon',
            title:"价格组",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/icon/pricegroup'),
          },
          {
            path: 'prouductlist',
            name: 'prouductlist',
            chinise:'设计',
            items:'icon',
            title:"商品列表",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/icon/prouductlist'),
          },
          {
            path: 'pinglunguanli',
            name: 'pinglunguanli',
            chinise:'设计',
            items:'icon',
            title:"评价管理",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/icon/pinglunguanli'),
          },
          {
            path: 'sucai',
            name: 'sucai',
            chinise:'素材',
            items:'transfer',
            title:"素材库",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/transfer/sucai'),
          },
          {
            path: 'gongdandetail',
            name: 'gongdandetail',
            chinise:'素材',
            items:'transfer',
            title:"工单明细",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/transfer/gongdandetail'),
          },
          {
            path: 'orderlsit',
            name: 'orderlsit',
            chinise:'优化师',
            items:'seo',
            title:"订单列表",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/seo/orderlist'),
          },
          {
            path: 'ordertongji',
            name: 'ordertongji',
            chinise:'优化师',
            items:'seo',
            title:"订单统计",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/seo/ordertongji'),
          },
          {
            path: 'shujufenxi',
            name: 'shujufenxi',
            chinise:'优化师',
            items:'seo',
            title:"数据分析",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/seo/shujufenxi'),
          },
          {
            path: 'guanggaocost',
            name: 'guanggaocost',
            chinise:'优化师',
            items:'seo',
            title:"广告费用导入",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/seo/guanggaocost'),
          },
          {
            path: 'productrenling',
            name: 'productrenling',
            chinise:'优化师',
            items:'seo',
            title:"商品认领",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/seo/productrenling'),
          },
          {
            path: 'prolist',
            name: 'prolist',
            chinise:'优化师',
            items:'seo',
            title:"商品列表",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/seo/prolist'),
          },

          {
            path: 'ordershenhe',
            name: 'ordershenhe',
            chinise:'客服',
            items:'seo',
            title:"订单列表",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/customerservice/ordershenhe'),
          },
          {
            path: 'daicheck',
            name: 'daicheck',
            chinise:'客服',
            items:'seo',
            title:"待审核",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/customerservice/daicheck'),
          },
          {
            path: 'daideliver',
            name: 'daideliver',
            chinise:'客服',
            items:'seo',
            title:"待发货",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/customerservice/daideliver'),
          },
          {
            path: 'problemorder',
            name: 'problemorder',
            chinise:'客服',
            items:'seo',
            title:"问题订单",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/customerservice/problemorder'),
          },
          {
            path: 'delete',
            name: 'delete',
            chinise:'客服',
            items:'seo',
            title:"已删除",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/customerservice/delete'),
          },
          {
            path: 'yicheck',
            name: 'yicheck',
            chinise:'客服',
            items:'seo',
            title:"已发货",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/customerservice/yicheck'),
          },
          {
            path: 'comment',
            name: 'comment',
            chinise:'客服',
            items:'seo',
            title:"商品评论",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/customerservice/comment'),
          },
          {
            path: 'buygoods',
            name: 'buygoods',
            chinise:'供应链',
            items:'supplychain',
            title:"货物采购",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/supplychain/buygoods'),
          },
          {
            path: 'purchaseDetails',
            name: 'purchaseDetails',
            chinise:'供应链',
            items:'supplychain',
            title:"采购明细",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/supplychain/purchaseDetails'),
          },
          {
            path: 'stock',
            name: 'stock',
            chinise:'供应链',
            items:'supplychain',
            title:"库存",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/supplychain/stock'),
          },
          {
            path: 'skuadmin',
            name: 'skuadmin',
            chinise:'供应链',
            items:'supplychain',
            title:"SKU管理",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/supplychain/skuadmin'),
          },
          {
            path: 'productmanagement',
            name: 'productmanagement',
            chinise:'SH物流',
            items:'SHlogistics',
            title:"产品管理",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/SHlogistics/productmanagement'),
          },
          {
            path: 'warehousingmanagement',
            name: 'warehousingmanagement',
            chinise:'SH物流',
            items:'SHlogistics',
            title:"入库管理",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/SHlogistics/warehousingmanagement'),
          },
          {
            path: 'outgoods',
            name: 'outgoods',
            chinise:'SH物流',
            items:'SHlogistics',
            title:"出库管理",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/SHlogistics/outgoods'),
          },
          {
            path: 'inventorymanagement',
            name: 'inventorymanagement',
            chinise:'SH物流',
            items:'SHlogistics',
            title:"库存管理",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/SHlogistics/inventorymanagement'),
          },
          {
            path: 'logistics_company',
            name: 'logistics_company',
            chinise:'SH物流',
            items:'SHlogistics',
            title:"物流公司管理",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/SHlogistics/addLogisticsCompany'),
          },
          {
            path: 'admin',
            name: 'admin',
            chinise:'系统设置',
            items:'permissions',
            title:"管理员列表",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/permissions/userlist'),
          },
          {
            path: 'rolelist_auth',
            name: 'rolelist_auth',
            chinise:'系统设置',
            items:'permissions',
            title:"角色列表",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/permissions/rolelist'),
          },
          {
            path: 'menu',
            name: 'menu',
            chinise:'系统设置',
            items:'permissions',
            title:"菜单API管理",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/permissions/menu'),
          },
          {
            path: 'sidebarmenu',
            name: 'sidebarmenu',
            chinise:'系统设置',
            items:'permissions',
            title:"侧边栏菜单管理",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/permissions/sidebarmenu'),
          },
          {
            path: 'operationlog',
            name: 'operationlog',
            chinise:'系统设置',
            items:'permissions',
            title:"操作日志",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/permissions/operationlog'),
          },
          {
            path: 'debuglog',
            name: 'debuglog',
            chinise:'系统设置',
            items:'permissions',
            title:"调试日志",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/permissions/debuglog'),
          },
          {
            path: 'systemConfiguration',
            name: 'systemConfiguration',
            chinise:'系统设置',
            items:'permissions',
            title:"系统配置",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/permissions/systemConfiguration'),
          },
          {
            path: 'uploadConfiguration',
            name: 'uploadConfiguration',
            chinise:'系统设置',
            items:'permissions',
            title:"上传配置",
            alone:false,
            iconCls:'el-icon-setting',
            component: ()=>import('@/views/permissions/uploadConfiguration'),
          },
      ]
    },
    {
      path: '*',
      name: 'NotFound',
      component: ()=>import('@/page404')
    },
  ]
})


export default router
